### ISSUE TITLE
hfst-SweNER download link broken.

### ISSUE THREAD

**Issue by spcsmrf** [spraakbanken/sparv-docs#1]
The download link to hfst-SweNER on this page redirects to the wrong page.
https://spraakbanken.gu.se/sparv/#/user-manual/installation-and-setup?id=hfst-swener

**Comment by anne17** [comment]
Thanks for pointing this out! I will try to find out where the download is available now!

**Comment by anne17** [comment]
I contacted the maintainer of hfst-SweNER and received the following persistent URL: http://urn.fi/urn:nbn:fi:lb-2021101202
The link now points to the correct location (fixed in  [this commit](https://github.com/spraakbanken/sparv-pipeline/commit/bd7da9ca267e7beb7dc159083c34a546581b3c67)). Thanks again for reporting this!
